### ISSUE TITLE
Browse MAS

### ISSUE THREAD

**Issue by y-u-s-u-f** [tonka3000/raycast-extension-ideas#3]
An extension to browse the Mac App Store. This could probably be achieved using the [MAS cli](https://github.com/mas-cli/mas)

**Comment by tonka3000** [comment]
This sounds quite interesting

**Comment by djpowers** [comment]
There is now the [Mac App Store Search](https://www.raycast.com/say4n/mac-app-store-search) extension available, so this issue might be able to be closed.
